### PR TITLE
fixed #1041: Potential crash in invokeJSTouchOneByOneCallback.

### LINKED ISSUE #1041: Potential  Crash in invokeJSTouchOneByOneCallback
0 JavaScriptCore | _llint_slow_path_get_by_id + 3924
-- | --
1 JavaScriptCore | _llint_slow_path_get_by_id + 80
2 JavaScriptCore | _llint_entry + 10612
3 JavaScriptCore | _vmEntryToJavaScript + 272
4 JavaScriptCore | JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 136
5 JavaScriptCore | JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 400
6 JavaScriptCore | JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 168
7 JavaScriptCore | JSObjectCallAsFunction + 368
8 ahzh-mobile | se::Object::call(std::__1::vector<se::Value, std::__1::allocator<se::Value> > const&, se::Object*, se::Value*) + 152
9 ahzh-mobile | invokeJSTouchOneByOneCallback(cocos2d::EventListenerTouchOneByOne*, TouchOneByOneType, cocos2d::Touch*, cocos2d::Event*, se::Value*) + 524
10 ahzh-mobile | std::__1::function<void (cocos2d::Touch*, cocos2d::Event*)>::operator()(cocos2d::Touch*, cocos2d::Event*) const + 44
11 ahzh-mobile | _ZNSt3__110__function6__funcIZN7cocos2d15EventDispatcher18dispatchTouchEventEPNS2_10EventTouchEE3$_3NS_9allocatorIS6_EEFbPNS2_13EventListenerEEEclEOSA_ + 292
12 ahzh-mobile | std::__1::function<bool (cocos2d::EventListener*)>::operator()(cocos2d::EventListener*) const+ 40
13 ahzh-mobile | cocos2d::EventDispatcher::dispatchEventToListeners(cocos2d::EventDispatcher::EventListenerVector*, std::__1::function<bool (cocos2d::EventListener*)> const&) + 208
14 ahzh-mobile | cocos2d::EventDispatcher::dispatchTouchEvent(cocos2d::EventTouch*) + 364
15 ahzh-mobile | cocos2d::EventDispatcher::dispatchEvent(cocos2d::Event*) + 208
16 ahzh-mobile | cocos2d::GLView::handleTouchesOfEndOrCancel(cocos2d::EventTouch::EventCode, int, long*, float*, float*) + 416
17 ahzh-mobile | -[CCEAGLView touchesEnded:withEvent:] + 504
18 UIKit | -[UIWindow _sendTouchesForEvent:] + 2544
19 UIKit | -[UIWindow sendEvent:] + 3208
20 UIKit | -[UIApplication sendEvent:] + 340
21 UIKit | ___dispatchPreprocessedEventFromEventQueue + 2364
22 UIKit | ___handleEventQueueInternal + 4760
23 UIKit | ___handleHIDEventFetcherDrain + 152
24 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
25 CoreFoundation | ___CFRunLoopDoSource0 + 88
26 CoreFoundation | ___CFRunLoopDoSources0 + 204
27 CoreFoundation | ___CFRunLoopRun + 1048
28 CoreFoundation | CFRunLoopRunSpecific + 436
29 GraphicsServices | GSEventRunModal + 100
30 UIKit | UIApplicationMain + 236
31 ahzh-mobile | main (main.m:8)
32 libdyld.dylib | _start + 4

### PR DESCRIPTION
**Pull request by dumganhar**
* 修复 invokeJSTouchOneByOneCallback 内潜在的崩溃问题
* 修复调用 director.getScheduler()/.getActionManager()/.getEventDispatcher() 返回临时 JS 对象被 Mark GC 后导致的潜在崩溃问题
* 在 EventDispather 中添加回调函数用于通知派发事件开始和结束
* 在 TextureCache 中添加回调函数用于通知纹理加入缓存与从缓存中移除
* 修复 event.stopPropagation() 停止所有触点的响应的问题
* 修复 EventDispatcher::updateListener 可能未被调用的问题

* fixed potential invalid se::Object after invoking cc.director.getScheduler/getActionManager/getEventDispatcher, cc.SpriteFrame/Sprite.getTexture.
* Added hook functions in EventDispatcher, TextureCache to prevent using dangerous se::Object.
* Stop propagation for TouchOneByOne event should only affect current Touch point.
* Fixed updateListener may not be invoked.

### CODE REVIEW

File: cocos/scripting/js-bindings/manual/jsb_cocos2dx_manual.cpp [hunk 1]
```diff
@@ -468,18 +461,6 @@ static bool invokeJSTouchOneByOneCallback(EventListenerTouchOneByOne* listener,
 
     } while(false);
 
-    if (type == TOUCH_ONE_BY_ONE_ON_TOUCH_BEGAN)
-    {
-        if (!(retVal->isBoolean() && retVal->toBoolean()))
-        {
-            arg1Obj->unroot();
```
Comment (dumganhar) [inline cocos/scripting/js-bindings/manual/jsb_cocos2dx_manual.cpp]: root / unroot are done in hook functions.

File: cocos/scripting/js-bindings/manual/jsb_cocos2dx_manual.cpp [hunk 2]
```diff
@@ -836,6 +819,89 @@ static bool js_EventListenerCustom_create(se::State& s)
...
+        if (touchEvent->getEventCode() == EventTouch::EventCode::BEGAN)
+        {
+            bool fromCache = true;
+            const auto& touches = touchEvent->getTouches();
+            for (auto&& touch : touches)
+            {
+                se::Value touchVal;
+                native_ptr_to_seval<Touch>(touch, __jsb_cocos2d_Touch_class, &touchVal, &fromCache);
+                assert(!fromCache);
+                touchVal.toObject()->root();
```
Comment (dumganhar) [inline cocos/scripting/js-bindings/manual/jsb_cocos2dx_manual.cpp]: Cocos2D-X reuses `Touch` pointer from touch began to touch ended(cancelled) when dispatching a touch event. We only need to root it from touch began and unroot it in touch ended(cancelled).

File: cocos/scripting/js-bindings/manual/jsb_cocos2dx_manual.cpp [hunk 3]
```diff
@@ -836,6 +819,89 @@ static bool js_EventListenerCustom_create(se::State& s)
...
+        assert(false);
+        return;
+    }
+
+    se::Value textureVal;
+    bool fromCache = false;
+    native_ptr_to_seval<Texture2D>(texture, __jsb_cocos2d_Texture2D_class, &textureVal, &fromCache);
+    if (!fromCache && textureVal.isObject())
+    {
+        iterOwner->second->attachObject(textureVal.toObject());
```
Comment (dumganhar) [inline cocos/scripting/js-bindings/manual/jsb_cocos2dx_manual.cpp]: After a texture being added to texturecache. Create a js object to associate with it to avoid dangerous se::Object being used.

File: cocos/scripting/js-bindings/script/jsb_cocos2d.js [hunk 4]
```diff
@@ -1089,3 +1089,57 @@ cc.GLProgram.prototype.setUniformLocationWithMatrix4fv = function(){
...
     this.setUniformLocationWithMatrixfvUnion.apply(this, tempArray);
 };
+
+// Hack for the lifecycle of JS objects
+cc.Director.prototype._jsb_getScheduler = cc.Director.prototype.getScheduler;
+cc.Director.prototype.getScheduler = function() {
+    var scheduler = this._jsb_getScheduler();
+    if (this._jsb_scheduler != scheduler)
+    {
+        this._jsb_scheduler = scheduler;
```
Comment (dumganhar) [inline cocos/scripting/js-bindings/script/jsb_cocos2d.js]: Prevent to reuse invalid scheduler binding object.
